branch-defaults:
  default:
    environment: Elenaudlastprbackend-env
  master:
    environment: Elenaudlastprbackend-env
environment-defaults:
  Elenaudlastprbackend-env:
    branch: null
    repository: null
global:
  application_name: elena-ud-last-pr-backend
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: www/Archive.zip